### ISSUE TITLE
Add social icons for Youtube, Discord, Substack in the Footer

### ISSUE THREAD

**Issue by srijani07** [SuperteamDAO/superteam-reputation#105]
<img width="1320" alt="image" src="https://github.com/SuperteamDAO/superteam-reputation/assets/72404928/c5ffea29-8f67-47bd-bf1c-5daefc7fb32f">

**Comment by ATREAY** [comment]
Hey @srijani07, can I work on this issue if it's open?

**Comment by srijani07** [comment]
@ATREAY yes!

**Comment by ATREAY** [comment]
Hey @srijani07, could I also get the logos for "Earn" and "Build"? It might look a bit odd to keep them as text only. Is it okay to leave them as text, or can we have logos for them?

**Comment by srijani07** [comment]
@ATREAY could you ping me on discord @srijani? i'll share all the logo files.

**Comment by ATREAY** [comment]
Hello @srijani07, I've substituted the textual representations of social links with their respective logos. Please take a look whenever you have a moment.
