### ISSUE TITLE
Design: Create a light mode theme design & color system

### ISSUE THREAD

**Issue by irffanasiff** [SuperteamDAO/superteam-reputation#12]
### Description:

A **Light mode** will help make the dashboard look better for people who prefer light mode. You can create a color system for it so that it is easy for developer to implement new theme.

### Deliverables:

A new light mode Figma design and color pallete for both dark and light mode

**Comment by razialam** [comment]
@irffanasiff can you assign this to me

**Comment by razialam** [comment]
<img width="273" alt="Screenshot 2022-12-13 at 4 46 09 PM" src="https://user-images.githubusercontent.com/90634143/207304306-a2e2264d-723e-4751-b47f-f2c5efa0772a.png">

discord tag- razivity#2369

**Comment by irffanasiff** [comment]
Thanks
