### ISSUE TITLE
Feature: Implement the new Design

### ISSUE THREAD

**Issue by irffanasiff** [SuperteamDAO/superteam-reputation#20]
### Description:

Implement the new header and footer design in the reputation dashboard. 
- [ ]  Move the search bar into header
- [ ] Add Sorting filter ( Sort xp from low to high and high to low )
- [ ] Add Medals to the weekly top contributors
- [ ] Implement the new Navbar in both light and dark theme
- [ ] Implement the new footer from the [design file](https://www.figma.com/file/Jh2OAdaBtgRakAuCOCV1jl/Reputation-system-file?node-id=0%3A1&t=MhXY0AhlA4whlmuX-1)

> Use the colors from the color system for both the light and dark theme.

**Comment by Sagargajare** [comment]
@irffanasiff 
Given API not returning lastSevenDaysData 
res.data.lastSevenDaysData is undefined
![image](https://user-images.githubusercontent.com/56780589/208233175-300514bc-4cf8-45c8-8b1a-96d5ab232a3b.png)

**Comment by irffanasiff** [comment]
can you try this backend url - https://api.reputation.superteam.fun/xp

**Comment by Sagargajare** [comment]
okay 
Thanks
should I update it .env.local.example aswell?

**Comment by irffanasiff** [comment]
updated it sync your fork

**Comment by Sagargajare** [comment]
okay

**Comment by Sagargajare** [comment]
for sorting should consider sorting by total XP or should be done for each skill

**Comment by irffanasiff** [comment]
by total xp for now

**Comment by Sagargajare** [comment]
Okay Thanks for quick response

**Comment by irffanasiff** [comment]
Listing the things which needs to be fixed.

- Please put the button on the right and dark/light mode switch to the left

- The button was for a menu which you forgot to implement, just check the header all the menu items are commented there and put it in the navbar. [Link to the code](https://github.com/SuperteamDAO/superteam-reputation/blob/aa92584f62459ef65b6a23c80c678c65f7657e79/src/components/Dashboard/DashboardHeader.tsx#L341)

- Remove all the navbar links for now because we don't have anything to put there ( will implement it in next version )

**Comment by irffanasiff** [comment]
### 1) need navbar design for mobile or how should the navbar look on mobile? 
- Remove the links to other pages and just keep the claimxp, superteam logo, and light/dark switch on mobile

### 2) need footer design for mobile or how should the footer look on mobile?
- will update the design please check the design file which i shared

### 3) Please verify colors if they are accurate if not let me know.
- i will do the colors dont worry about them 😉

### 4) Sorting is done. if you feel it can be improved let me know
- implement the select option for sorting will add more sorting options in future i will add the menu design in the figma file.

**Comment by Sagargajare** [comment]
okay

**Comment by irffanasiff** [comment]
@Sagargajare updated the design please check, try the color pallet provided in `chakra.config.ts` and use the colors from there and try to match them with the design

When the xp is sort from low to high please fix the medals ( don't show the medals when filter is applied )
![Screenshot 2022-12-18 at 3 03 42 PM](https://user-images.githubusercontent.com/74172466/208291079-4af22916-8558-4148-8145-af3844586f1e.png)

**Comment by irffanasiff** [comment]
allocate `30 XP` to @Sagargajare
