### ISSUE TITLE
New: mobile responsive project page

### ISSUE THREAD

**Issue by irffanasiff** [SuperteamDAO/superteam-reputation#26]
### Description:

Make the projects page mobile responsive same as the home page

**Comment by rohan-201** [comment]
What type of

**Comment by Sagargajare** [comment]
@irffanasiff 

Content of rows is different on projects page from the rows we have on homepage. 

Can u provide design for row on project page?

**Comment by rohan-201** [comment]
Yesi can can you contact on discors my id is Drac#6969

**Comment by rohan-201** [comment]
I ment discord

**Comment by irffanasiff** [comment]
just do some adjustments and make it we will create a new design after holidays

**Comment by Sagargajare** [comment]
@irffanasiff if it's done then u can close the 
issue.

**Comment by Sagargajare** [comment]
@irffanasiff if it's done then u can close the
issue.
