### ISSUE TITLE
New: A summary/context about the Superteam XP system on the landing page

### ISSUE THREAD

**Issue by paarugsethi** [SuperteamDAO/superteam-reputation#37]
An intro about the Superteam Reputation system and what XP means within the DAO would be helpful on a public facing landing page

**Comment by irffanasiff** [comment]
write it in the dummy text are above the search bar as shown in the design <img width="547" alt="Screenshot 2023-01-16 at 11 07 35 PM" src="https://user-images.githubusercontent.com/74172466/212737839-2283a3a1-105c-4c90-b0d9-6ea9b966c5a3.png">

**Comment by simplysabir** [comment]
Does this Still need work?
