### ISSUE TITLE
Add social links to people's profiles in the lists

### ISSUE THREAD

**Issue by paarugsethi** [SuperteamDAO/superteam-reputation#39]
Since this is the public facing page of the DAO, a twitter/linkedin link next to people's names who have contributed to it would be great so people can reach the top contributors easily.

**Comment by simplysabir** [comment]
hey, can i work on this issue?

**Comment by paarugsethi** [comment]
> 

Send a PR and we'll merge it if @irffanasiff approves!

**Comment by irffanasiff** [comment]
we dont have users twitter or linkedin data as of now the only information we can use is their discord id which is the user name, so if you can do anything with that

**Comment by simplysabir** [comment]
yeah i guess discord will be better to even reach out. will keep updating about the progress here.

**Comment by simplysabir** [comment]
Hey, @irffanasiff from where should i take member details (e.g. discord id) i'm expecting it to be from `pages/projects.tsx`

I'm new to Open Source so i moight misunderstood some code and things. that's why asking it here.

**Comment by akshatcoder-hash** [comment]
Hey @irffanasiff! I would love to work on this issue. Could you please assign it to me?

**Comment by irffanasiff** [comment]
go with it discuss with @simplysabir if he is not working on it then

**Comment by simplysabir** [comment]
Hey, I'm still on it. Kinda figured out the solution but if i don't able to raise a PR within 2 days then surely you can go ahead.

**Comment by simplysabir** [comment]
Hey @akshatcoder-hash , you can go ahead and if you want to discuss anything or want any help just hmu
