### ISSUE TITLE
Empty states for the XP table

### ISSUE THREAD

**Issue by Aarushe** [SuperteamDAO/superteam-reputation#41]
Designs for empty state of XP dashboard

**Comment by irffanasiff** [comment]
Can you add the link for the design frame here so that it will be easy to review

**Comment by irffanasiff** [comment]
waiting for your response

**Comment by irffanasiff** [comment]
@Aarushe what is the latest on this issue

**Comment by Aarushe** [comment]
https://www.figma.com/file/HnuwmqM8BArEHM9sFLPjgU/superteam-reputation-feedback?node-id=236%3A4834&t=aZV3VcTrY9MgRMeD-1
