### ISSUE TITLE
Add new colors to the theme

### ISSUE THREAD

**Issue by irffanasiff** [SuperteamDAO/superteam-reputation#48]
Add new colors to the chakraUI theme for the new design check - issue [#40](https://github.com/SuperteamDAO/superteam-reputation/issues/40)

**Comment by arihantbansal** [comment]
can take this up!

**Comment by irffanasiff** [comment]
sure go with it

**Comment by arihantbansal** [comment]
can I get the figma file / color palette list?

**Comment by irffanasiff** [comment]
https://www.figma.com/file/HnuwmqM8BArEHM9sFLPjgU/superteam-reputation-feedback?node-id=171%3A1644&t=rKcuwZAqZqBCtHZJ-1

**Comment by irffanasiff** [comment]
yo @arihantbansal what is the latest on this issue are you working on it

**Comment by arihantbansal** [comment]
resolved the conflict, safe to merge now.
