### ISSUE TITLE
Top Contributors of the Week

### ISSUE THREAD

**Issue by irffanasiff** [SuperteamDAO/superteam-reputation#49]
We need a new design for top contributors of the week in the header section

**Comment by irffanasiff** [comment]
can you add the file link @Aarushe

**Comment by Aarushe** [comment]
> 

https://www.figma.com/file/HnuwmqM8BArEHM9sFLPjgU/superteam-reputation-feedback?node-id=194%3A1905&t=y991YfFiw4UkkOAJ-1
