### ISSUE TITLE
Fix: Seach bar

### ISSUE THREAD

**Issue by irffanasiff** [SuperteamDAO/superteam-reputation#5]
### Description:

The current search bar is very basic and does not show search result **while clearing the input**. 
Notice while clearing the input it does not render the results for **yas**

![reputationgif](https://user-images.githubusercontent.com/74172466/206891411-4360cc9f-89ee-4b72-b790-fce9e56401c3.gif)

### Expected behavior:

The Search result should be shown even if we clear the input letters for every backspace click, like the the normal behaviour of a search bar

### Additional context

Make sure you go through the [contributor guidelines](https://github.com/SuperteamDAO/superteam-reputation/blob/prod/.github/CONTRIBUTORS.md), If you need any help or assistance while working on it you can start a conversation below.

**Comment by vrajdesai78** [comment]
@irffanasiff I want to work on this issue

**Comment by kes11av** [comment]
need a staging/prod backend url. also would recommend having checks to validate env variables are present

**Comment by irffanasiff** [comment]
> need a staging/prod backend url. also would recommend having checks to validate env variables are present

@OverAcheiever check .env.local.example

**Comment by irffanasiff** [comment]
@vrajdesai78 the best pr in the shortest time span will be merged, do it in the best way ( UX wise ) and as soon as possible. 

If anyone is working on the issue this is how the PR's will be merged. Be quick and the best.

**Comment by shockz09** [comment]
> need a staging/prod backend url. also would recommend having checks to validate env variables are present

yeah ,
@irffanasiff please see to this

**Comment by namanchordia** [comment]
hey, 
its not working at all for me when I switch to the members tab

**Comment by namanchordia** [comment]
![image](https://user-images.githubusercontent.com/81012600/206921035-1600ec93-48cd-4eca-aef0-aec5b9d80484.png)

**Comment by irffanasiff** [comment]
Merged @OverAcheiever PR. We will release a clear guideline on how PR's will be selected and how to setup the project
