### ISSUE TITLE
Projects page expanded view

### ISSUE THREAD

**Issue by Aarushe** [SuperteamDAO/superteam-reputation#51]
https://www.figma.com/file/HnuwmqM8BArEHM9sFLPjgU/superteam-reputation-feedback?node-id=0%3A1&t=jqEj30SEmg6ZzLXw-1

**Comment by irffanasiff** [comment]
can you make a clear page of final designs there are too many and i am not able to see which is the final one

**Comment by irffanasiff** [comment]
Design - https://www.figma.com/file/HnuwmqM8BArEHM9sFLPjgU/superteam-reputation-feedback?node-id=310%3A2519&t=4YL7IMhukFo3rLXH-1
