### ISSUE TITLE
User XP timeline

### ISSUE THREAD

**Issue by irffanasiff** [SuperteamDAO/superteam-reputation#52]
check the design here - [#43]( https://github.com/SuperteamDAO/superteam-reputation/issues/43)

**Comment by irffanasiff** [comment]
> 

test

**Comment by ameya-deshmukh** [comment]
Hey @irffanasiff, open to take up?

**Comment by thisissamridh** [comment]
Hey @irffanasiff  , can I be assigned with this issue
