### ISSUE TITLE
Top Contributors of the week

### ISSUE THREAD

**Issue by irffanasiff** [SuperteamDAO/superteam-reputation#53]
check issue #49 for design

**Comment by arihantbansal** [comment]
can take this up

**Comment by irffanasiff** [comment]
go with it dude

**Comment by irffanasiff** [comment]
is this done @arihantbansal

**Comment by arihantbansal** [comment]
> is this done @arihantbansal

will make the pr by the weekend, just a a bit of styling left

**Comment by irffanasiff** [comment]
hii @arihantbansal what is the progress on this one

**Comment by arihantbansal** [comment]
> hii @arihantbansal what is the progress on this one

hey, the landing page background as per the figma design hasn't been implemented yet, which hinders the progress of this issue as the background color for the weekly top widget is the same as the page background right now. otherwise it's ready. I'll make a PR
