### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by Aarushe** [SuperteamDAO/superteam-reputation#54]
https://www.figma.com/file/HnuwmqM8BArEHM9sFLPjgU/superteam-reputation-feedback?node-id=194-1904

**Comment by arihantbansal** [comment]
what needs to be done here?

**Comment by skdonepudi** [comment]
@irffanasiff @Aarushe  I'm working on it. Can you assign it to me?

**Comment by irffanasiff** [comment]
yes go with it and one of you pick up another issue we have a lot of them 😁

**Comment by irffanasiff** [comment]
let me know what is the status of this one @skdonepudi

**Comment by skdonepudi** [comment]
Hey @irffanasiff , almost done. Will create a PR by this weekend.
