### ISSUE TITLE
Ops skill not visible under Superteam Earn in /projects

### ISSUE THREAD

**Issue by irffanasiff** [SuperteamDAO/superteam-reputation#60]
When project detailed section is toggled under skills part - ops skills are not visible https://reputation.superteam.fun/projects

![Image](https://user-images.githubusercontent.com/74172466/231676546-9819a4c2-cf50-4357-a54d-f325e99686be.png)

**Comment by avneesh0612** [comment]
Can I take this up?

**Comment by irffanasiff** [comment]
assigned it to you buddy go with it 🫡

**Comment by irffanasiff** [comment]
@avneesh0612 are you working on it

**Comment by avneesh0612** [comment]
srijani told me that the rep page is going to get a revamp a while back, so I was waiting for that

**Comment by srijani07** [comment]
new design is live - https://www.figma.com/file/s32xd6gRmFSufVyJrC6Btl/Superteam-Reputation?node-id=29%3A688&t=H0uejTcmfLBY4I0Q-1

@avneesh0612 you can start working on this - let me know if you need anything!

**Comment by avneesh0612** [comment]
okay, will do!
