### ISSUE TITLE
Contributors tab shows 404 error

### ISSUE THREAD

**Issue by irffanasiff** [SuperteamDAO/superteam-reputation#61]
![Image](https://user-images.githubusercontent.com/74172466/231678473-77bcc5c3-8f74-4b13-afcd-fe40a73e3795.png)

**Comment by avneesh0612** [comment]
From what I see there are no contributors in the db. What do we want to show here?

**Comment by irffanasiff** [comment]
for that checkout the backend for reputation or maybe ping @srijani07 or @dhruvsol on discord

**Comment by avneesh0612** [comment]
alright sounds good

**Comment by srijani07** [comment]
hey, hey - working with aarushe on the new design, will not need the contributors page. 
we will now have a single page called "Community" with all details on both members and contributors - let me circle up with dhruv on the backend deets!

**Comment by avneesh0612** [comment]
Sounds good

**Comment by irffanasiff** [comment]
this is fixed closing it
