### ISSUE TITLE
Minor Fixes

### ISSUE THREAD

**Issue by irffanasiff** [SuperteamDAO/superteam-reputation#62]
- “Open Bounties” in the Claim XP list on the top right is not needed
-  Change copy - “Everyone” to “All Community”

**Comment by thearyanag** [comment]
gm ser, can you assign this to me.

**Comment by irffanasiff** [comment]
it is yours my man 🫡

**Comment by irffanasiff** [comment]
@thearyanag what is the latest update on it are you working on it ro should i assign it to someone else

**Comment by thearyanag** [comment]
@irffanasiff the changes were already completed, but due to some issue of URL at that point was unable to push, will push it now.

**Comment by thearyanag** [comment]
@irffanasiff facing error at get https://reputation-backend-production.up.railway.app/api/v1/xp/projects while building the app.

**Comment by arihantbansal** [comment]
> @irffanasiff facing error at get https://reputation-backend-production.up.railway.app/api/v1/xp/projects while building the app.

Try this url: https://reputation-backend-production-1e2d.up.railway.app/api/v1/xp/projects
