### ISSUE TITLE
Add country flag before the name of member/user

### ISSUE THREAD

**Issue by srijani07** [SuperteamDAO/superteam-reputation#75]
![Image](https://user-images.githubusercontent.com/74172466/237053903-f31678f7-4da5-4156-af9f-cfb55751fd10.png)

**Comment by irffanasiff** [comment]
we have to see if the data is available in the backend in order to show it

**Comment by srijani07** [comment]
hey, the data is available in the airtable - would that be enough?
i still don't fully understand the custom backend and don't think there's any documentation for it.
