### ISSUE TITLE
Remove the Weekly Top section

### ISSUE THREAD

**Issue by srijani07** [SuperteamDAO/superteam-reputation#76]

**Comment by thisissamridh** [comment]
<img width="396" alt="Screenshot 2023-05-15 at 7 51 24 PM" src="https://github.com/SuperteamDAO/superteam-reputation/assets/69411088/397db1e2-c96e-4f8d-b6df-88f38a153b37">

Do we want to remove this part from the page .

can I be assigned with the issue

**Comment by srijani07** [comment]
correct @thisissamridh!
